---
Server:
  ServerHost: localhost,
  ServerPort : 3333
Client:
  ClientHost: localhost,
  ClientPort: 3333
Redis:  
  Host: localhost,
  Port: 6379,
HashcashZerosCount: 3,
HashcashDuration": 300,
HashcashMaxIterations: 1000000